Repository hoon25/GrapIt, pull requests merged in 2023-01, with the labels that each got.

#10 [#6] React코드 기능 확인 완료
  grapit-react/src/App.js
  grapit-react/src/css/Rtcchat.css
  grapit-react/src/index.css
  grapit-react/src/routes/Chat.js
  grapit-react/src/routes/ChatRoom.js
  grapit-react/src/routes/RtcChat.js
  grapit-react/src/routes/TwoDGraph.js
  grapit-react/src/routes/graph/CircleInputGroup.js
  grapit-react/src/routes/graph/GraphList.js
  grapit-react/src/routes/graph/GraphTypeButton.js
  grapit-react/src/routes/graph/LineInputGroup.js
  grapit-react/src/routes/graph/TwoDGraph.js
Labels: In progress, Asking for Review, Refactor

#15 [#13] 기능 구현 및 React 동작 확인 완료
  grapit-react/src/css/Rtcchat.css
  grapit-react/src/routes/RtcChat.js
  grapit-react/src/routes/graph/CircleInputGroup.js
  grapit-react/src/routes/graph/GraphInputGroup.js
  grapit-react/src/routes/graph/GraphList.js
  grapit-react/src/routes/graph/GraphTypeButton.js
  grapit-react/src/routes/graph/LineInputGroup.js
  grapit-react/src/routes/graph/TwoDGraph.js
  grapit-spring/src/main/java/edu/oak/grapitspring/chat/ChatController.java
  grapit-spring/src/main/java/edu/oak/grapitspring/chat/ChatDTO.java
  grapit-spring/src/main/java/edu/oak/grapitspring/chat/MemoryChatRepository.java
Labels: In progress

#16 2D그래프 구현 완료 후 merge 요청
  grapit-react/src/css/Rtcchat.css
  grapit-react/src/routes/RtcChat.js
  grapit-react/src/routes/graph/CircleInputGroup.js
  grapit-react/src/routes/graph/GraphInputGroup.js
  grapit-react/src/routes/graph/GraphList.js
  grapit-react/src/routes/graph/GraphTypeButton.js
  grapit-react/src/routes/graph/LineInputGroup.js
  grapit-react/src/routes/graph/TwoDGraph.js
  grapit-spring/src/main/java/edu/oak/grapitspring/chat/ChatController.java
  grapit-spring/src/main/java/edu/oak/grapitspring/chat/ChatDTO.java
  grapit-spring/src/main/java/edu/oak/grapitspring/chat/MemoryChatRepository.java
Labels: Asking for Review

#31 [#21] Tutor, Tutor찾기 API 설계
  grapit-spring/src/main/java/edu/oak/grapitspring/tutor/FindTutorDTO.java
  grapit-spring/src/main/java/edu/oak/grapitspring/tutor/MemoryTutorRepository.java
  grapit-spring/src/main/java/edu/oak/grapitspring/tutor/TutorEntity.java
  grapit-spring/src/main/java/edu/oak/grapitspring/tutor/TutorFindController.java
  grapit-spring/src/main/java/edu/oak/grapitspring/tutor/TutorFindService.java
  grapit-spring/src/main/java/edu/oak/grapitspring/tutor/TutorRepository.java
  grapit-spring/src/main/java/edu/oak/grapitspring/tutor/genderType.java
  grapit-spring/src/main/java/edu/oak/grapitspring/tutor/gradeType.java
  grapit-spring/src/main/java/edu/oak/grapitspring/tutor/rankingType.java
Labels: Asking for Review

#18 [#17] 기능 구현 및 React 동작 확인 완료
  grapit-react/package.json
  grapit-react/public/index.html
  grapit-react/src/App.css
  grapit-react/src/App.js
  grapit-react/src/components/Canvas.js
  grapit-react/src/components/Cursor.js
  grapit-react/src/components/FloatingButton.js
  grapit-react/src/components/common/header/Header.jsx
  grapit-react/src/components/fabric/assets/images/tools-28.png
  grapit-react/src/components/fabric/assets/images/tools-polygon.png
  grapit-react/src/components/fabric/board/drawer/arrow.js
  grapit-react/src/components/fabric/board/drawer/circle.js
  grapit-react/src/components/fabric/board/drawer/dotline.js
  grapit-react/src/components/fabric/board/drawer/ellipse.js
  grapit-react/src/components/fabric/board/drawer/index.js
  grapit-react/src/components/fabric/board/drawer/line.js
  grapit-react/src/components/fabric/board/drawer/polygon.js
  grapit-react/src/components/fabric/board/drawer/rectangle.js
  grapit-react/src/components/fabric/board/drawer/text.js
  grapit-react/src/components/fabric/board/drawer/triangle.js
  grapit-react/src/components/fabric/board/index.js
  grapit-react/src/components/fabric/board/style.scss
  grapit-react/src/components/fabric/index.d.ts
  grapit-react/src/components/fabric/index.js
  grapit-react/src/components/fabric/style.scss
  grapit-react/src/components/fabric/toolbar/colorpicker/index.js
  grapit-react/src/components/fabric/toolbar/colorpicker/style.scss
  grapit-react/src/components/fabric/toolbar/index.js
  grapit-react/src/components/fabric/toolbar/style.scss
  grapit-react/src/components/fabric/toolbar/thickness/index.js
  grapit-react/src/components/fabric/toolbar/thickness/style.scss
  grapit-react/src/components/fabric/utils/handler.js
  grapit-react/src/components/fabric/utils/mode.js
  grapit-react/src/config/liveblocks.config.js
  grapit-react/src/css/Canvas.css
  grapit-react/src/css/Rtcchat.css
  grapit-react/src/css/cursor.css
  grapit-react/src/css/floatingButton.css
  grapit-react/src/css/vidu.css
  grapit-react/src/index.css
  grapit-react/src/navbar.jsx
  grapit-react/src/pages/ForgetPasswordPage.js
  grapit-react/src/pages/HomePage.js
  grapit-react/src/pages/LandingPage.js
  grapit-react/src/pages/LoginPage.js
  grapit-react/src/pages/RegisterPage.js
  grapit-react/src/routes/Canvas.js
  grapit-react/src/routes/CollaborationPage.js
  grapit-react/src/routes/RtcChat.js
  grapit-react/src/routes/TestVidu.js
  grapit-react/src/routes/Vidu.js
  grapit-react/src/routes/graph/TwoDGraph.js
  grapit-react/src/store.js
  grapit-react/src/store/isWhiteBoardSlice.js
  grapit-react/src/store/toolbarInfoSlice.js
  grapit-react/src/utils/getContrastingColor.js
  grapit-react/src/utils/useBoundingClientRectRef.js
  grapit-spring-socket/src/main/java/edu/oak/grapitsocket/textchat/ChatDTO.java
Labels: In progress, Refactor

#43 Feature/#17/ubs4939
  grapit-react/src/components/fabric/board/drawer/circle.js
  grapit-react/src/components/fabric/board/index.js
  grapit-react/src/routes/graph/GraphInputGroup.js
  grapit-react/src/routes/graph/TwoDGraph.js
Labels: In progress, Asking for Review

#58 Feature/#13/ubs4939
  grapit-react/src/components/2D/TwoCardBox.jsx
  grapit-react/src/components/2D/TwoDGraphInput.jsx
  grapit-react/src/components/2D/TwoDimensionSideBar.jsx
  grapit-react/src/components/2D/input/CircleInputGroup.jsx
  grapit-react/src/components/2D/input/LineInputGroup.jsx
  grapit-react/src/components/2D/input/TwoDInputGroup.jsx
  grapit-react/src/components/Canvas.js
  grapit-react/src/components/fabric/index.js
  grapit-react/src/components/fabric/style.scss
  grapit-react/src/components/fabric/toolbar/index.js
  grapit-react/src/components/home/hero/Hero.jsx
  grapit-react/src/components/home/hero/hero.css
  grapit-react/src/css/Rtcchat.css
  grapit-react/src/routes/RtcChat.js
  grapit-react/src/routes/equationBoard/EquationHandBoard.js
  grapit-react/src/routes/graph/GraphInputGroup.js
  grapit-react/src/routes/graph/GraphList.js
  grapit-react/src/routes/graph/GraphTypeButton.js
  grapit-react/src/routes/graph/TwoDGraph.js
  grapit-react/src/routes/vidu/UserVideo.css
  grapit-react/src/routes/vidu/UserVideoComponent.js
  grapit-react/src/routes/vidu/Vidu.js
  grapit-react/src/store.js
  grapit-react/src/store/TwoDInputSlice.js
  grapit-react/src/store/TwoDfigureSlice.js
  grapit-react/src/store/toolbarInfoSlice.js
  package.json
Labels: In progress, Refactor
